### PR TITLE
Fixed failing test

### PR DESCRIPTION
**Pull request by toymachiner62**
Simple fix to a failing test.

### CODE REVIEW

**Comment by wzrdtales** [comment]
This is actually failing for me:

```
··········· ··· ··················✗············ · ··························· ··················· ··········· ··················· ·····  
   
   
    addIndex has resulting index metadata 
      ✗ with additional index 
        »        
        actual expected 
         
        Eevent 
         // mysql_test.js:371 
  ✗ Broken » 126 honored ∙ 1 broken (53.115s) 
  npm ERR! Test failed.  See above for more details.
```

I will take a look and look for a solution.

**Comment by wzrdtales** [comment]
Ok I see, one db supports case sensitivity and one does not. An additional check within the test suite is needed that first detects if it is case sensitive or insensitive.

**Comment by wzrdtales** [comment]
Ok actually it doesn't make sense to check if case sensitivity is used or not, in this tests, because this isn't anything that is related to the driver. It has to do with the operating system filesystem. In my case arch linux, with a filesystem that is case sensitive.
Another reason why I decided not to check for case sensitivity is, that you can explicitly disable it for table names via: lower_case_table_names

That means the tests do not run into a failure, instead I would suggest to lower case everything.

**Comment by toymachiner62** [comment]
I'm running on OSX and all i did was run these commands as your docs show:
> mysql -u root -e "CREATE DATABASE db_migrate_test;"
> createdb db_migrate_test

and then `$ npm test` and I got that error.

**Comment by wzrdtales** [comment]
Yes as pointed out in the last comment, mac os x and windows use by default case insensitive file systems. With this tables which get created on the disk are also created in lower case.

I will push a commit that lower case all names in this test.

**Comment by toymachiner62** [comment]
Oh ok. I wasn't sure if you meant that I needed to change a setting on my db.

**Comment by wzrdtales** [comment]
Unfortunately I'm currently still waiting for Jeff to activate Travis CI. But I think he will do this on the weekend, this will ease much :)

**Comment by wzrdtales** [comment]
@toymachiner62 Have overseen some, eventType was also upper case. Changed to event_type, you can rebase against the master now.

**Pull request closed without merging**
