### PR TITLE
Add `var` keywords in front of `dbm` declaration in templates.

### LINKED ISSUE #240: Missing 'var' in template
When creating a new migration, the template is missing a 'var' keyword. I think it might be [here](https://github.com/kunklejr/node-db-migrate/blob/master/lib/migration.js#L56). 
I don't see it right away as I am using the `--sql-file` option to keep the database code in SQL, and I don't look at the top level migration file.

This does't affect db-migrates ability to run on my local machine, but it fails (`dbm not defined`) during our deploy script that is run through continuous integration, which in return fails to migrate the database and causes problems.

This is fixed by adding 'var' in front of the first line in the migration file (in the template here: https://github.com/kunklejr/node-db-migrate/blob/master/lib/migration.js#L56).

### PR DESCRIPTION
**Pull request by forstermatth**
fixes #240, adds the missing var statements.

### CODE REVIEW

**Comment by forstermatth** [comment]
[This](https://github.com/kunklejr/node-db-migrate/blob/master/test/driver/mongodb_test.js#L152) assertion failed. I don't know why.

**Comment by wzrdtales** [comment]
See https://github.com/kunklejr/node-db-migrate/issues/240#issuecomment-77518362

This is not a bug, but intended to handle the problem with NODE_PATH.

**Comment by wzrdtales** [comment]
I will do the the following instead:

dbm moves into the global object. This shouldn't make problems anymore.

**Comment by wzrdtales** [comment]
Moved into global namespace and published as patch in version v0.9.8

fixes #240

**Pull request closed without merging**
